services:
    doctrine_cache_invalidation.listener.invalidation:
        class: Goksagun\DoctrineCacheInvalidationBundle\EventListener\DoctrineCacheInvalidationListener
        #arguments: ["@service_id", "plain_value", "%parameter%"]
        tags:
            - { name: doctrine.event_listener, event: onFlush }
        calls:
            - [ setLogger, ['@?logger'] ]
